### ISSUE TITLE
Airport Missing

### ISSUE THREAD

**Issue by knotknot1** [ip2location/ip2location-iata-icao#10]
Kansai International Airport commonly known as 関空 (Kankū) (IATA: KIX, ICAO: RJBB)

Missing

**Comment by knotknot1** [comment]
Chengdu Tianfu International Airport (IATA: TFU, ICAO: ZUTF)

**Comment by ip2location** [comment]
Hi knotknot1,

We have updated the outdated IATA code, and added missing airport and IATA code. Thank you for the findings!
