### ISSUE TITLE
Sphinx International Airport has incorrect coordinates

### ISSUE THREAD

**Issue by williw33** [ip2location/ip2location-iata-icao#13]
in iata-icao.csv:
"EG","Al Jizah","SPX","","Sphinx International Airport","29.5083","-95.0514"

Given Lat/long coordinates are located in the US. Lat/long should be approximately be 30.110, 30.895

**Comment by ip2location** [comment]
Hi williw33,

We have investigated and fixed the coordinates in our file. Thanks for reporting this to us!
