### ISSUE TITLE
Xieng Khouang Airport

### ISSUE THREAD

**Issue by jeffk4** [ip2location/ip2location-iata-icao#14]
The Latitude coordinate for Xieng Khouang Airport is incorrect.  It should be 19.448378506948977.

**Comment by ip2location** [comment]
Hi jeffk4,

Thanks for reporting this issue. We have updated the latitude according to https://geohack.toolforge.org/geohack.php?pagename=Xieng_Khouang_Airport&params=19_26_24.54_N_103_10_6.24_E_type:airport.
