### ISSUE TITLE
A lot of incorrect or outdated ICAO codes.

### ISSUE THREAD

**Issue by olehz** [ip2location/ip2location-iata-icao#15]
For instance:
IST: LTBA => LTFM
CZW: EPCH => EPRU
SRP: ENSA => ENSO
... etc

**Comment by ip2location** [comment]
H olehz,

Thank you for reporting the issue. We are working on verifying the ICAO codes. Meanwhile you can create a PR and update those outdated ICAO codes, since this is a open-source list.
