### ISSUE TITLE
United States airports registered in India and with incorrect data

### ISSUE THREAD

**Issue by elisma** [ip2location/ip2location-iata-icao#21]
While looking at why the Indianapolis International Airport was missing from the US listing i saw that it indeed exists but its listed in India instead of the US and with wrong region name, not sure if coordinates are correct though

"IN","Gujarat","IND","KIND","Indianapolis International Airport","39.7173","-86.2944"

Some others i found just with a quick glance

"IN","Gujarat","RCR","KRCR","Fulton County Airport","41.0656","-86.1817"

"IN","Gujarat","MIE","KMIE","Delaware County Regional Airport","40.2423","-85.3959"

"IN","Gujarat","FWA","KFWA","Fort Wayne International Airport","40.9785","-85.1951"

**Comment by ip2location** [comment]
Hi @elisma ,

Thanks for reporting the issue. We had identified and fixed those Indiana airports that mislabeled as India airports.
