### ISSUE TITLE
CSV headers missing

### ISSUE THREAD

**Issue by SammySkycrafts** [ip2location/ip2location-iata-icao#22]
The last commit has removed the CSV column headers. The first line is now the first line of data, whereas before it was the column header. Was this intentional? If not, could these be added back? Below is the headers which were there prior to commit 52bb397

`"country_code","region_name","iata","icao","airport","latitude","longitude"`

**Comment by ip2location** [comment]
Hi Sammy,

Thanks for reporting the issue. We had updated with the header back.
