### ISSUE TITLE
Duplicate ICAO codes

### ISSUE THREAD

**Issue by Velek** [ip2location/ip2location-iata-icao#26]
I'm processing this file and I get an error using the ICAO code as an index.
"PK","Punjab","SWN","OPSW","Sahiwal Airport","31.8894","72.3917"
"PK","Sindh","RZS","OPSW","Sawan Airport","26.9662","68.8781"
"MM","Mandalay","NYT","VYNT","Naypyidaw Airport","19.6235","96.201"
"MM","Shan","NMT","VYNT","Namtu Airport","23.083","97.383"
"AU","Western Australia","CKW","YCHK","Graeme Rowley Aerodrome","-22.3543","119.643"
"AU","Western Australia","CXQ","YCHK","Christmas Creek Airport","-22.3567","119.652"

**Comment by ip2location** [comment]
Hi @Velek,

We have checked the duplicate issue and had updated the list. You may download the latest release (https://github.com/ip2location/ip2location-iata-icao/releases/tag/1.0.15).
