### ISSUE TITLE
Missing Key Airports

### ISSUE THREAD

**Issue by tdshokies** [ip2location/ip2location-iata-icao#27]
Hi Team - I was reviewing the data set and it appears that we are missing some key airports. Can these please be reviewed and added. Thanks so much for your support. 

GRU - Sao Paulo Guarulhos
CGH - Sao Paulo Congonhas
VCP - Sao Paulo Viracopos
PKX - Beijing Daxing
SDU - Rio De Janeiro Dumont
CNF - Belo Horizonte Confins
BSL - Basel/Mulhouse Euroairport
BMA - Stockholm Bromma
YEG - Edmonton International
GIG - Rio De Janeiro International

**Comment by ip2location** [comment]
The database is open source. Feel free to contribute pull request.
