### ISSUE TITLE
Incorrect lat/long?

### ISSUE THREAD

**Issue by axenic** [ip2location/ip2location-iata-icao#32]
US,California,PYS,,Paradise Skypark,-51.6867,-57.7785
SO,Sanaag,LKR,,Las Khorey Airport,36.084,-115.154
US,Missouri,OSB,,Grand Glaize-Osage Beach Airport,36.3058,43.1474

**Comment by ip2location** [comment]
Hi axenic,

Thanks for the reporting. We have checked and updated the lat and long of the mentioned airports, and released a new version.
