### ISSUE TITLE
Duplicate airports

### ISSUE THREAD

**Issue by Macintosh-Fan** [ip2location/ip2location-iata-icao#35]
_(Accidentally typed shift-enter into the browser, because I still need to write the description.)_

**Comment by Macintosh-Fan** [comment]
I originally wrote a C program to check for distances between airports around the world, and I found some airports with possible duplicate entries: https://www.mapcustomizer.com/map/Duplicates

**Comment by ip2location** [comment]
Hi @Macintosh-Fan,

The link is unavailable now, if you have the list, kindly reopen this issue with the list attached.
