### ISSUE TITLE
Airport designated in the wrong country

### ISSUE THREAD

**Issue by Macintosh-Fan** [ip2location/ip2location-iata-icao#36]
`Razer Airport (KUR/OARZ), Badakhshan, AF` is placed next to `Williamson County Regional Airport (MWA/KMWA), Illinois, US` in the United States.

**Comment by Macintosh-Fan** [comment]
I'll also include:
- `Jajao Airport (JJA/AGJO), Isabel, SB` next to `Juina Airport (JIA/SWJN), Mato Grosso, BR` in Brazil.
- `Oban Airport (OBA/-), Queensland, AU` next to `Oban Airport (North Connel Airport) (OBN/EGEO), Scotland, GB` in Scotland.

**Comment by ip2location** [comment]
Hi @Macintosh-Fan,

We didn't found the issue in the latest release. Therefore, we will close the issue now. Should you have found the issue again, you may reopen this issue or create a new issue ticket.
