### ISSUE TITLE
Duplicate Airport - CYKM Kincardine Municipal Airport

### ISSUE THREAD

**Issue by joshdaws0n** [ip2location/ip2location-iata-icao#7]
https://github.com/ip2location/ip2location-iata-icao/blob/7256d1120c34474b1cb9b716c1fa8db06ef9cec8/iata-icao.csv#L1826

I've been using this table as the basis of an airport list for a project and spotted a duplicate when parsing the CSV. Not sure if intentional or not!

**Comment by ip2location** [comment]
Thank you for the input. We are sorry for the issue and we have fixed it.
